# Generated by Django 3.1.3 on 2020-12-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_title', models.CharField(max_length=100)),
                ('res_spec', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
