# Generated by Django 3.1.3 on 2020-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tfd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='res_image',
            field=models.ImageField(default='', upload_to='Tfd/images'),
        ),
    ]
