# Generated by Django 3.1.3 on 2020-12-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tfd', '0003_restaurant_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tfd.restaurant')),
            ],
        ),
    ]
