# Generated by Django 3.1.3 on 2021-01-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tfd', '0006_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
